### ISSUE TITLE
[BUG] in package.json scripts on Windows, \n gobbles the rest of the script

### ISSUE THREAD

**Issue by sciepsilon** [npm/read-package-json#96] opened 2020-10-04 03:29 UTC
# What / Why
In an npm package.json script on Windows, `\n` gobbles the rest of the command. 

## When
* A package.json script contains `\n`

## Where
* npm scripts declared in package.json

My environment is:
- Windows PowerShell 5.1.18362.752
- npm 6.14.6
- node v12.18.4

### Current Behavior
Everything until the `\n` is executed. Everything after the `\n` is ignored.

### Steps to Reproduce
In `package.json`:
```json
{
  "scripts": {
    "bad": "echo a\nb && echo c"
  }
}
```

In Windows Powershell:
```
npm run bad
```

Output (note that everything except the last line is a reprint of the command, so really the command's output is just "a"):
```

> mypkg@1.0.0 bad C:\My\Location
> echo a
b && echo c

a
```

### Expected Behavior
`\n` is a common sequence when writing scripts for Mac or Linux, so I expect it not to break unrelated parts of the script when running on Windows. `\n` could be treated literally, which is the normal PowerShell behavior, or it could be treated like the empty string, `` `n `` (the Powershell newline sequence), or `n`. 

## Who
* n/a

## References
 * May be a bug in [npm/run-script](https://github.com/npm/run-script), rather than a bug in `npm/read-package-json`. I have cross-posted there.

**Comment by isaacs** [comment] 2020-10-27 23:18
duplicate of https://github.com/npm/run-script/issues/8, the package.json file is being read just fine.

**Closed by isaacs** 2020-10-27 23:18 UTC
